---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "pip"
    directory: "/ovoenergy"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
