---
name: "Build"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-python-linux.yml@dee521f49caa2626c8adeed2af4767887b2f202b # 20261009.1
