---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    uses: timmo001/workflows/.github/workflows/dependency-review.yml@942a2e735c957787562e621d916fb6f78c9bb508 # 20261009.0
