---
name: "Lint"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@master
  lint-markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@master
  lint-markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@master
  lint-pylint:
    name: Lint (pylint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt -r requirements_test.txt
          pip install "pylint>=3.2"
      - name: Run pylint (uses pyproject.toml)
        run: |
          pylint --rcfile=pyproject.toml ovoenergy
  lint-ruff:
    uses: timmo001/workflows/.github/workflows/lint-ruff.yml@master
