---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@2fb2fa1ffdd2f4808768bf86828482660e366a13 # 20261008.3
