---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@f8d0daf26e163f0ee997d759fbf0f7daeb598c43 # 20261008.2
